# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: khalil1
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: alluser
# "service" is the name of this project. This will also be added to your AWS resource names.
service: AllUser

provider:
  name: aws
  runtime: nodejs20.x

  vpc:
    securityGroupIds:
      - sg-0ed40a5999e1650e0
    subnetIds:
      - subnet-0dbe603c213c8c82d
      - subnet-0bff18fbd7188e54b
      - subnet-03484be23648c333e
  environment:
    DB_HOST: posystemdb.cjeu04uek25d.us-east-1.rds.amazonaws.com
    DB_USER: admin
    DB_PASSWORD: posystem01
    DB_NAME: POSystemdb
    DB_PORT: 3306

functions:
  getAllUsers:
    handler: handler.getAllUsers
    timeout: 30
    events:
      - http:
          path: users
          method: get

plugins:
  - serverless-offline
