org: khalil1

app: deleteuser

service: deleteuser

provider:
  name: aws
  runtime: nodejs20.x

  vpc:
    securityGroupIds:
      - sg-0ed40a5999e1650e0
    subnetIds:
      - subnet-0dbe603c213c8c82d
      - subnet-0bff18fbd7188e54b
      - subnet-03484be23648c333e
  environment:
    DB_HOST: posystemdb.cjeu04uek25d.us-east-1.rds.amazonaws.com
    DB_USER: admin
    DB_PASSWORD: posystem01
    DB_NAME: POSystemdb
    DB_PORT: 3306

functions:
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
